import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Preloader from '@/components/Preloader'
import QuickView from '@/components/QuickView/QuickView'
import Newsletter from '@/components/Newsletter'
import ScrollToTop from '@/components/ScrollToTop'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Preloader />
				<Header />
				{children}
				<Footer />
				<QuickView />
				<Newsletter />
				<ScrollToTop />
			</body>
		</html>
	)
}
